on: [push]
name: Deploy

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CGEN_URL: ${{ secrets.CGEN_URL }}
          envkey_BASE_URL: ${{ secrets.BASE_URL }}
          envkey_GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          envkey_GRAPHQL_AUTH_KEY: ${{ secrets.GRAPHQL_AUTH_KEY }}
          envkey_IP_URL: ${{ secrets.IP_URL }}
          envkey_IP_KEY: ${{ secrets.IP_KEY }}
          file_name: .env

      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/urlrouter:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/urlrouter:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'cgen-url-router'
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/urlrouter:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
